stages:
  - "build"
  - "container-build"
  - "deploy"

build-backend:
  image: ${DOCKER_CACHE}/node:14-alpine
  stage: "build"
  artifacts:
    untracked: false
    paths:
      - backend/bundle.js
    expire_in: 1 days
  script:
    - cd backend/
    - npm i
    - npm install -g esbuild
    - npm run build
    - esbuild ./dist/index.js --bundle --outfile=bundle.js --platform=node

build-frontend:
  image: ${DOCKER_CACHE}/node:14-alpine
  stage: "build"
  artifacts:
    untracked: false
    paths:
      - frontend/build
    expire_in: 1 days
  script:
    - cd frontend/
    - npm i
    - npm run build

build-backend-container:
  stage: "container-build"
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint: [""]
  needs:
    - build-backend
  script:
    - echo "DATABASE_URL=\"${DATABASE_URL}\"" > backend/.env
    - echo "BASE_URL='https://eps-dev.net'" >> backend/.env
    - echo "FRONTEND_URL='https://s.eps-dev.net'" >> backend/.env
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.cdev.nexus\":{\"auth\":\"$(printf "%s:%s" "${PRIVATE_REG_USER}" "${PRIVATE_REG_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "registry.cdev.nexus/url-shortener/backend:${CI_COMMIT_REF_SLUG}"
      --destination "registry.cdev.nexus/url-shortener/backend:latest"

build-frontend-container:
  stage: "container-build"
  image:
    name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint: [""]
  needs:
    - build-frontend
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.cdev.nexus\":{\"auth\":\"$(printf "%s:%s" "${PRIVATE_REG_USER}" "${PRIVATE_REG_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "registry.cdev.nexus/url-shortener/frontend:${CI_COMMIT_REF_SLUG}"
      --destination "registry.cdev.nexus/url-shortener/frontend:latest"

deploy-backend:
  stage: deploy
  image:
    name: 'registry.cdev.nexus/devops/kubernetes:latest'
    entrypoint: [""]
  needs:
    - build-backend-container
  script:
    - helm uninstall url-backend --namespace url-shortener || true
    - helm install url-backend ./deployments/backend --values ./deployments/backend/values.yaml --namespace url-shortener
  only:
    - main

deploy-frontend:
  stage: deploy
  image:
    name: 'registry.cdev.nexus/devops/kubernetes:latest'
    entrypoint: [""]
  needs:
    - build-frontend-container
  script:
    - helm uninstall url-frontend --namespace url-shortener || true
    - helm install url-frontend ./deployments/frontend --values ./deployments/frontend/values.yaml --namespace url-shortener
  only:
    - main
